### ISSUE TITLE
(5) improve CI test pipeline

### ISSUE THREAD

**Issue by NedHenry** [UCSCLibrary/dams_project_mgmt#410] opened 2020-11-18 18:12 UTC
Ned needs some time to do maintenance on the CI pipeline, making sure it automatically runs relevant acceptance tests and monitors test coverage through Coverall. More info to be added to this ticket soon.

Related:
#76 #376 #256 #372 #377

**Comment by rmjaffe** [comment] 2020-11-18 19:31
@NedHenry Is CI Jenkins Pipeline Maintenance #354 a dupe of this card?

**Closed** 2021-01-13 18:57 UTC
