### ISSUE TITLE
(2) UA50 Titles Not Displaying Semi-Colons

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/dams_project_mgmt#141] opened 2019-12-04 22:37 UTC
### Descriptive Summary

Objects in the UA50 collection that have semi-colons in their titles in the ingest spreadsheet are not displaying correctly. A backslash is appearing instead of the semi-colon.

### Background 

Example: https://digitalcollections.library.ucsc.edu/concern/works/9s161736t

### Expected Behavior 

Object titles display semi-colons ( ; ), matching what is on the ingest spreadsheet. 

### Actual Behavior

A backslash ( \ ) appears where a semi-colon ( ; ) should be.

**Comment by NedHenry** [comment] 2019-12-20 19:21
This was caused by an ingest bug that was present when these works were ingested. Semicolons are used in our ingest spreadsheet to separate multiple metadata values in the same spreadsheet cell. Literal semicolons in metadata values are preceded by a forward slash '\;' to tell the ingest software not to separate into multiple values. In these cases, the spreadsheet was formatted correctly but the forward slash escape character was not recognized by the ingest software, and the title was broken into two with the forward slash at the end of the first title.
I fixed the metadata on all of these works. I believe that the ingest issue has been addressed and solved since this collection was ingested, but I should go back and make sure that is part of our rspec tests (and/or write to test for that and make sure it passes).

For now I believe this issue has been resolved, though it couldn't hurt to have someone else look at the works in question and make sure you don't see any problems I might have missed.

**Comment by kellyChex** [comment] 2020-01-09 20:04
I looked at https://digitalcollections.library.ucsc.edu/concern/works/9s161736t and saw a backslash. @JessWaggs How best should we test the rest? I see 12340 works under the UCSC Photography Services Photographs collection.

**Comment by JessWaggs** [comment] 2020-01-09 21:51
I think a spot check would be sufficient? Though I'm not sure how many titles have semi-colons.

@rmjaffe Do you know how many titles have semi-colons?

**Comment by rmjaffe** [comment] 2020-01-09 23:21
If you want to reference the ingest metadata, it's in the dams_ingest share.  In spending under 10 min on this, it looks like there are 136 titles containing 396 semi-colons.

**Comment by JessWaggs** [comment] 2020-01-10 00:01
I spot checked about 20 of the records and all of them appear correct now.

([This page](https://digitalcollections.library.ucsc.edu/collections/jd472x03h?cq=john&locale=en&page=3&per_page=100&sort=score+desc%2C+system_create_dtsi+desc&view=list) provides a good dozen or so alone)

**Comment by kellyChex** [comment] 2020-01-10 20:42
Awesome! Closed this one.

**Closed by kellyChex** 2020-01-10 20:42 UTC
Labels: bug
