### ISSUE TITLE
Bug: Unable to add Works

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#170] opened 2020-01-22 23:25 UTC
# Current Behavior: 

When you click 'Add new work' nothing happens 
![Image 2020-01-22 at 3 26 54 PM](https://user-images.githubusercontent.com/9621070/72943838-f1552a80-3d2b-11ea-95f1-718e7fe858ae.png) 

# Expected Behavior: 

1. Go to **http://digitalcollections.library.ucsc.edu/dashboard/works?locale=en#**  
2. See a modal to select a work type 
![Screen Shot 2020-01-22 at 3 42 47 PM](https://user-images.githubusercontent.com/9621070/72944485-df748700-3d2d-11ea-8d87-b8eb3f3f725e.png)
3. See a form like this: 
![Screen Shot 2020-01-22 at 3 27 32 PM](https://user-images.githubusercontent.com/9621070/72944344-81e03a80-3d2d-11ea-8c08-ea73d9c17f8b.png)

**Comment by NedHenry** [comment] 2020-01-29 20:28
This seems to be caused by a javascript error affecting the admin dashboard. I will look into it soon.
`TypeError: this.data is not a function`

**Comment by NedHenry** [comment] 2020-01-29 22:01
Looks like this error is caused by a script that is meant to load manifest files for the universal viewer (`uv_manifest_ajax.js`). This file should never have been committed to the master branch. It must have been added at some point by mistake. I removed it and fixed the problem.

**Closed by NedHenry** 2020-01-29 22:01 UTC

**Comment by kellyChex** [comment] 2020-01-30 01:42
Ok, thank you!
