### ISSUE TITLE
(2) Determine what types of files should be displayed in the Universal Viewer 

### ISSUE THREAD

**Issue by kellyChex** [UCSCLibrary/dams_project_mgmt#34] opened 2019-10-08 22:36 UTC
### Descriptive Summary

The Universal Viewer is great because of the additional functionality such as being able to zoom in and out of a photo. However, it does take a while to load. We may not want it to be the default viewer for simple objects where researchers just need to view it quickly. Of course, we'll need to consider how complicated this will be for development. 

###Notes

Should it be driven by the work type (simple vs complex), file type (.tiff, pdf, etc.), or collection? 
The team needs to review the Porter Collection, http://digitalcollections-staging.library.ucsc.edu/collections/df65v8619, before we come to a decision on what types of files and formats we want to have displayed in the UV by default.

**Comment by NedHenry** [comment] 2019-10-16 22:13
Just a few notes about this: 
Currently simple image object load without the universal viewer by default. The user can click on the image to load it in the universal viewer optionally.
Also, we are currently having performance issues that seem to be primarily related to complex object display in the Universal Viewer (Issue #36). I would prefer not to publish any complex image objects using Universal Viewer until that issue has been satisfactorily resolved.

**Comment by kellyChex** [comment] 2019-10-22 02:05
@rmjaffe I believe this ticket was inspired by the performance issues we came across in the UV. Ned makes a good point that viewing images in the UV are optional. Do you think we can close this one?

**Comment by rmjaffe** [comment] 2019-10-22 17:11
If I recall there were a couple different questions/ideas at play here:

1) Do we want all image objects to load/appear in UV by default?
2) Do we want some images to appear in UV by default?  If so, based on which criteria?  Simple/complex? File types?

The performance issues we observed were somewhat separate from this conversation, but were nudging us away from having everything display in UV by default.  It think this issue and this round of conversation is closed, but it may come up again once the performance issues are resolved.  Sorry, those were a lot of words to say "sure, close it."

**Comment by kellyChex** [comment] 2019-10-22 18:15
Benchmark for image loader. If hit those benchmarks then make UV the default. If not, then just default for complex objects.

**Comment by kellyChex** [comment] 2019-11-19 19:23
Ned will load images into production and see how fast they load.

**Comment by chesleyperry** [comment] 2019-11-19 19:51
Here are a couple of tools that grade webpage load times:
[Web Page Test ](http://www.webpagetest.org/)
[Pingdom ](https://tools.pingdom.com/)

The universal viewer is a little hard to test since the images are opening in an iFrame but these tools might be a good start.

**Comment by NedHenry** [comment] 2019-11-26 18:54
After improving the performance of our image server significantly, the universal viewer is performing well enough to provide a solid user experience. Nonetheless, it is a relatively heavyweight tool that is not usually necessary for viewing single images. We wanted to determine whether loading the UV has a small enough effect on performance that it is worth loading by default, or whether we should load it on command when specified by the user. 
To answer this, I've compared the load times and performance of simple image objects loading with and without the Universal Viewer. The short answer is that loading the UV does come with enough of a cost in terms of speed and server resources that we should only load it when the user asks (for simple image objects). 
When testing in my own browser, both on and off the VPN, I measured between 0.3 and 1 seconds difference in load times with and without the Universal Viewer (depending on how you measure it and how much is already cached in your browser). The exact load times weren't super consistent when measured this way, so I won't reproduce them here. These test didn't seem to offer an obvious conclusion, so I used some online page speed analysis tools to compare a simple image page with and without the UV. 
These tools detected a large difference between the two, with the UV-enable image loading much slower and getting a poorer rank. One tool measured that the UV increased our page load time from 1s to 3s, and also gave the UV-enabled page a much poorer rank because of some header and javascript convention issues. Even if some of those issues are not immediately vital for our primary user experience (it doesn't seem to take 3s to load from northern california), nonetheless the results of these types of automatic analysis tools are important for SEO. The primary item pages that we link to from other systems should perform decently in page ranking tools in order to be ranked will in search engines. For this reason if no other, I think we should load single image objects without the UV by default.

**Comment by NedHenry** [comment] 2019-11-26 18:57
For complex objects, the UV still seems to be the fastest/easiest way to get a nice user experience. Still, based on these tests, it is clear that a simple gallery or lightbox display would perform better, especially on automated page ranking tests. Down the line if we want to further optimize our SEO, we could consider having the UV be optional for complex objects as well.

**Comment by NedHenry** [comment] 2019-11-26 18:59
Also, I'd like to note that while the Universal Viewer still is relatively slow by the standards of professional websites, the crippling performance issues we were facing in #36 have been solved. The UV loads at least 10x faster than before for complex objects.

**Comment by JessWaggs** [comment] 2019-11-26 19:41
Would it be possible to make this invisible to the user by having a simple image load in the UV once the user clicks the zoom or full screen options?

![SimpleImage](https://user-images.githubusercontent.com/6412857/69666756-9c55aa80-1041-11ea-9e44-9fb24f20e3bf.png)

**Comment by NedHenry** [comment] 2019-11-26 20:19
I don't see why not. We'd have to make our own buttons outside the UV that mimick the ones on the UV for it to look transparent, but i think that wouldn't be too hard.

**Comment by JessWaggs** [comment] 2019-11-26 20:50
Great - that sounds good to me!

**Comment by kellyChex** [comment] 2019-11-28 00:56
@JessWaggs I just created a story to have the expand and zoom buttons trigger the UV view: https://github.com/UCSCLibrary/dams_project_mgmt/issues/138

**Comment by kellyChex** [comment] 2019-11-28 01:04
@chesleyperry @rmjaffe Will wait for you both to review Ned's assessment before closing.

**Comment by rmjaffe** [comment] 2019-12-02 18:23
@kellyChex Is the question here, "Do we want all image objects to load in UV by default?"

**Comment by chesleyperry** [comment] 2019-12-02 20:48
Given Ned's analysis, I think it makes good sense to load only the compound objects in the UV by default.  Jess's user story in #138 describes the desired behavior for triggering the UV view.

**Closed** 2019-12-03 19:03 UTC
Labels: Complex Objects Modeling, UI/UX
